# Generated by Django 2.1.4 on 2019-01-09 21:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


def populate_objects(apps, schema_editor):
    Team = apps.get_model('teams', 'Team')
    Membership = apps.get_model('teams', 'Membership')
    Invite = apps.get_model('teams', 'Invite')
    Request = apps.get_model('teams', 'Request')
    for team in Team.objects.all():
        for member in team.members.all():
            Membership(user=member, team=team).save()
        for invite in team.invites.all():
            # This isn't guaranteed to be correct, but it seems nicer than allowing Invite.by to be null
            Invite(user=invite, team=team, by=team.members.first()).save()
        for request in team.invites.all():
            Request(user=request, team=team).save()


def populate_fields(apps, schema_editor):
    Membership = apps.get_model('teams', 'Membership')
    Invite = apps.get_model('teams', 'Invite')
    Request = apps.get_model('teams', 'Request')
    for membership in Membership.objects.all():
        membership.team.members.add(membership.user)
    for invite in Invite.objects.all():
        invite.team.invites.add(invite.user)
    for request in Request.objects.all():
        request.team.requests.add(request.user)



class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userinfo'),
        ('teams', '0002_auto_20180513_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites_sent', to='accounts.UserInfo')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserInfo')),
            ],
        ),
        migrations.RunPython(
            code=populate_objects,
            reverse_code=populate_fields,
        ),
        migrations.RemoveField(
            model_name='team',
            name='invites',
        ),
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.RemoveField(
            model_name='team',
            name='requests',
        ),
    ]
