# Generated by Django 3.2.16 on 2022-11-12 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0008_auto_20220127_2354'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE teams_team_members RENAME TO teams_teammembership',
                    reverse_sql='ALTER TABLE teams_teammembership RENAME TO teams_team_members',
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='TeamMembership',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
                        ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'abstract': False,
                    },
                ),
                migrations.AlterField(
                    model_name='team',
                    name='members',
                    field=models.ManyToManyField(blank=True, related_name='teams', through='teams.TeamMembership', to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
