# Generated by Django 3.2.9 on 2021-11-18 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def populate_attendance_user(apps, schema_editor):
    Attendance = apps.get_model('events', 'Attendance')
    for attendance in Attendance.objects.all():
        attendance.user = attendance.user_info.user
        attendance.save()


def populate_attendance_user_info(apps, schema_editor):
    Attendance = apps.get_model('events', 'Attendance')
    for attendance in Attendance.objects.all():
        attendance.user_info = attendance.user.info
        attendance.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_auto_20211118_0924'),
        ('events', '0011_auto_20210515_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='user_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserInfo'),
        ),
        migrations.RunPython(
            code=populate_attendance_user,
            reverse_code=populate_attendance_user_info,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('event', 'user')},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='user_info',
        ),
    ]
