# Generated by Django 3.2.7 on 2021-09-26 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20210515_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='script_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='events.eventfile'),
        ),
        migrations.AddField(
            model_name='event',
            name='style_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='events.eventfile'),
        ),
    ]
