# Generated by Django 3.2.9 on 2021-11-30 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20211118_0943'),
        ('events', '0012_event_index_text'),
    ]

    operations = [
    ]
