# Generated by Django 3.2.12 on 2022-03-15 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20210926_2239'),
        ('events', '0013_merge_0012_auto_20211118_0943_0012_event_index_text'),
    ]

    operations = [
    ]
