# TODO: Replace with an official image when available
image: registry.gitlab.com/citygro/docker-and-compose

variables:
  DOCKER_DRIVER: overlay
  TEST_IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  RELEASE_IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
  SERVICE: web

services:
  - docker:dind

stages:
  - build
  - test

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - IMAGE_TAG=$TEST_IMAGE_TAG docker-compose build --pull
    - docker-compose push

test:
  stage: test
  script:
    - docker-compose pull
    - docker-compose run $SERVICE test
