version: '2.1'

services:
  poetry:
    entrypoint: poetry
    environment:
      PATH: /opt/hunter2/venv/bin:/root/.poetry/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      VIRTUAL_ENV: /opt/hunter2/venv
    image: ${PYTHON_IMAGE_TAG:-registry.gitlab.com/hunter2.app/hunter2/python:latest}
    volumes:
      - ${PWD:-.}:/opt/hunter2/src
  dot:
    command: -v -Tsvg -o/files/diagram/models.svg /files/diagram/models.dot
    image: registry.gitlab.com/rconan/docker-graphviz:3.0.0-6@sha256:89d8564f33363dd5114fed9518c465611e964f788622c0398c99aa8c85d17830
    volumes:
      - ${PWD:-.}:/files
  eslint:
    command: ["."]
    image: registry.gitlab.com/rconan/docker-eslint:8.19.0-4@sha256:11f37e6ebcb6302aa2076f702832f4f450de06d229c5cbd0f2a985edee1e98cc
    volumes:
      - ${PWD:-.}:/code
  flake8:
    image: registry.gitlab.com/rconan/docker-flake8:4.0.0-20@sha256:801910c93fb5fb6f5236c30035d7e558dfc3a849526f9487d07ef87c18767ca2
    volumes:
      - ${PWD:-.}:/code
  docs:
    environment:
      - H2_IMAGE_VERSION
    image: registry.gitlab.com/hunter2.app/hunter2/app:${H2_IMAGE_VERSION:-latest}
    volumes:
      - ${PWD:-.}:/opt/hunter2/src

