version: '2.1'

services:
  poetry:
    entrypoint: poetry
    environment:
      PATH: /opt/hunter2/venv/bin:/root/.poetry/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      VIRTUAL_ENV: /opt/hunter2/venv
    image: ${PYTHON_IMAGE_TAG:-registry.gitlab.com/hunter2.app/hunter2/python}
    volumes:
      - ${PWD:-.}:/opt/hunter2/src
  dot:
    command: -v -Tsvg -o/files/diagram/models.svg /files/diagram/models.dot
    image: registry.gitlab.com/rconan/docker-graphviz:2.47.1-8@sha256:d005f2c1f9759a38b8012ec58ffb13354e78cf8f4915c5f8bad76d5c4874ffac
    volumes:
      - ${PWD:-.}:/files
  eslint:
    command: ["."]
    image: registry.gitlab.com/rconan/docker-eslint:7.32.0-5@sha256:12ee203d9c9faa0b48519db521d3a09fb7a44257eb4db63348ff0eca406c3109
    volumes:
      - ${PWD:-.}:/code
  flake8:
    image: registry.gitlab.com/rconan/docker-flake8:3.7.9-31@sha256:6faacf293c45a125f612e4e3855367fbd542ce27e7327ce8262130d8979775aa
    volumes:
      - ${PWD:-.}:/code
