version: '2.1'

services:
  dot:
    command: -v -Tsvg -o/files/models.svg /files/models.dot
    image: registry.gitlab.com/rconan/docker-graphviz:0.0.1
    volumes:
      - ${PWD:-.}:/files
  flake8:
    image: registry.gitlab.com/rconan/docker-flake8:0.0.3
    volumes:
      - ${PWD:-.}:/code
