version: '2.1'

services:
  poetry:
    entrypoint: poetry
    environment:
      PATH: /opt/hunter2/venv/bin:/root/.poetry/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      VIRTUAL_ENV: /opt/hunter2/venv
    image: ${PYTHON_IMAGE_TAG:-registry.gitlab.com/hunter2.app/hunter2/python@sha256:b0fb6ca2a4789f0a2bd8551fd08be9bfcdf4719336192c3c181f68113cd32d9d}
    volumes:
      - ${PWD:-.}:/opt/hunter2/src
  dot:
    command: -v -Tsvg -o/files/diagram/models.svg /files/diagram/models.dot
    image: registry.gitlab.com/rconan/docker-graphviz:2.47.1-10@sha256:e8b65727d861a5a79ec4c2d50b1e1841274eabca06457881cc8adfa686b712b4
    volumes:
      - ${PWD:-.}:/files
  eslint:
    command: ["."]
    image: registry.gitlab.com/rconan/docker-eslint:8.1.0-0@sha256:fca4e3cf11e530e3fb8e7640951123d7ebe6e0361934b70f7a4fa9f9689a4d17
    volumes:
      - ${PWD:-.}:/code
  flake8:
    image: registry.gitlab.com/rconan/docker-flake8:3.7.9-31@sha256:6faacf293c45a125f612e4e3855367fbd542ce27e7327ce8262130d8979775aa
    volumes:
      - ${PWD:-.}:/code
  docs:
    image: ${APP_IMAGE_TAG:-registry.gitlab.com/hunter2.app/hunter2/app@sha256:7b6ea42a8828ec84147705fed933fc7d501b0ee6bc93234966d67b8771fb960e}
    volumes:
      - ${PWD:-.}:/opt/hunter2/src

