version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: images/app/Dockerfile
    environment:
      # Test run needs permission to create databases
      - H2_DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - H2_DATABASE_USER=postgres
      - H2_TEST_SEED
  websocket:
    build:
      context: .
      dockerfile: images/app/Dockerfile
    environment:
      # Test run needs permission to create databases
      - H2_DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - H2_DATABASE_USER=postgres
      - H2_TEST_SEED
  db:
    build: images/db
    environment:
      - POSTGRES_PASSWORD
  metrics:
    build: images/metrics
  web:
    build: images/web
