version: '2.1'

services:
  poetry:
    entrypoint: poetry
    environment:
      PATH: /opt/hunter2/venv/bin:/root/.poetry/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      VIRTUAL_ENV: /opt/hunter2/venv
    image: ${PYTHON_IMAGE_TAG:-registry.gitlab.com/hunter2.app/hunter2/python:latest}
    volumes:
      - ${PWD:-.}:/opt/hunter2/src
  dot:
    command: -v -Tsvg -o/files/diagram/models.svg /files/diagram/models.dot
    image: registry.gitlab.com/rconan/docker-graphviz:3.0.0-4@sha256:fe06be709392aa9582606f8ec348737b5bf565b5151a30b0e60bec74cfb3c80b
    volumes:
      - ${PWD:-.}:/files
  eslint:
    command: ["."]
    image: registry.gitlab.com/rconan/docker-eslint:8.19.0-3@sha256:12ba5f548803ec17a825b1fffe56260e7fe6369061cd04019d5c8780e16fe56e
    volumes:
      - ${PWD:-.}:/code
  flake8:
    image: registry.gitlab.com/rconan/docker-flake8:4.0.0-19@sha256:a573ec1ed1027244125db6eccc6057e0626559c671eebfe250d289b0233b0280
    volumes:
      - ${PWD:-.}:/code
  docs:
    environment:
      - H2_IMAGE_VERSION
    image: registry.gitlab.com/hunter2.app/hunter2/app:${H2_IMAGE_VERSION:-latest}
    volumes:
      - ${PWD:-.}:/opt/hunter2/src

