version: '2.1'

services:
  poetry:
    entrypoint: poetry
    environment:
      PATH: /opt/hunter2/venv/bin:/root/.poetry/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      VIRTUAL_ENV: /opt/hunter2/venv
    image: ${PYTHON_IMAGE_TAG:-registry.gitlab.com/hunter2.app/hunter2/python:latest}
    volumes:
      - ${PWD:-.}:/opt/hunter2/src
  dot:
    command: -v -Tsvg -o/files/diagram/models.svg /files/diagram/models.dot
    image: registry.gitlab.com/rconan/docker-graphviz:3.0.0-26@sha256:bc7a00a3524f2f948f3552baa7595c2f000490a892064a91e28e60f6621d7545
    volumes:
      - ${PWD:-.}:/files
  eslint:
    command: ["."]
    image: registry.gitlab.com/rconan/docker-eslint:8.25.0-1@sha256:b44defa437fb4be2b3fe0ef98064e8c57564767f6b4baa3fcc461a981e4debee
    volumes:
      - ${PWD:-.}:/code
  flake8:
    image: registry.gitlab.com/rconan/docker-flake8:5.0.0-13@sha256:7ec8906aba14fc64e1fa6fa5ca98455efd774593cebc42ebabb78b41c4d3a04a
    volumes:
      - ${PWD:-.}:/code
  docs:
    environment:
      - H2_IMAGE_VERSION
    image: ${H2_REGISTRY:-registry.gitlab.com/hunter2.app/hunter2}/app:${H2_IMAGE_VERSION:-latest}
    volumes:
      - ${PWD:-.}:/opt/hunter2/src

