version: '2.1'

services:
  poetry:
    entrypoint: poetry
    environment:
      PATH: /opt/hunter2/venv/bin:/root/.poetry/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      VIRTUAL_ENV: /opt/hunter2/venv
    image: ${PYTHON_IMAGE_TAG:-registry.gitlab.com/hunter2.app/hunter2/python:latest}
    volumes:
      - ${PWD:-.}:/opt/hunter2/src
  dot:
    command: -v -Tsvg -o/files/diagram/models.svg /files/diagram/models.dot
    image: registry.gitlab.com/rconan/docker-graphviz:3.0.0-22@sha256:5b06343efd8915d35e2569cd89d5ca93ab51091e167d8db056c45832a2344485
    volumes:
      - ${PWD:-.}:/files
  eslint:
    command: ["."]
    image: registry.gitlab.com/rconan/docker-eslint:8.23.1-7@sha256:2c5d2322a08d60b2206cb9f54fdf0a8ae4a092e21a99dd51c952ff4214e3ec4d
    volumes:
      - ${PWD:-.}:/code
  flake8:
    image: registry.gitlab.com/rconan/docker-flake8:5.0.0-9@sha256:d837709f0cb9ea886d6a062898a261ffb1393b564e736f0e2c6e48cbd93df0d2
    volumes:
      - ${PWD:-.}:/code
  docs:
    environment:
      - H2_IMAGE_VERSION
    image: ${H2_REGISTRY:-registry.gitlab.com/hunter2.app/hunter2}/app:${H2_IMAGE_VERSION:-latest}
    volumes:
      - ${PWD:-.}:/opt/hunter2/src

