version: '2.1'

services:
  db:
    image: postgres:9.6.10-alpine
    volumes:
      - db:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - db
    environment:
      - H2_DEBUG
      - H2_DOMAIN
      - H2_TEST_SEED
      - H2_SENDFILE=sendfile.backends.nginx
      - H2_SENTRY_DSN
    image: ${IMAGE_TAG:-registry.gitlab.com/hunter2.app/hunter2/app}
    volumes:
      - ${PWD:-.}:/usr/src/app
      - config:/config
      - uploads_events:/uploads/events
      - uploads_puzzles:/uploads/puzzles
      - uploads_solutions:/uploads/solutions
  web:
    build: ./nginx
    depends_on:
      - app
    image: ${IMAGE_TAG:-registry.gitlab.com/hunter2.app/hunter2/web}
    networks:
      default:
        aliases:
          - www.hunter2.local
          - dev.hunter2.local
    ports:
      - "8080:80"
    volumes:
      - uploads_events:/media/events:ro
      - uploads_puzzles:/media/puzzles:ro
      - uploads_solutions:/media/solutions:ro
  selenium_hub:
    image: selenium/hub:3.14.0-europium
  selenium_chrome:
    image: selenium/node-chrome-debug:3.14.0-europium
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium_hub
      - HUB_PORT_4444_TCP_PORT=4444
    ports:
      - "5900:5900"
    depends_on:
      - selenium_hub
  selenium_firefox:
    image: selenium/node-firefox-debug:3.14.0-europium
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium_hub
      - HUB_PORT_4444_TCP_PORT=4444
    ports:
      - "5901:5900"
    depends_on:
      - selenium_hub

volumes:
  db: {}
  config: {}
  uploads_events: {}
  uploads_puzzles: {}
  uploads_solutions: {}
