version: '3.5'

services:
  app:
    build: .
    environment:
      # Test run needs permission to create databases
      - H2_DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - H2_DATABASE_USER=postgres
      - H2_TEST_SEED
    image: ${APP_IMAGE_TAG:-registry.gitlab.com/hunter2.app/hunter2/app}
  db:
    build: postgres
    environment:
      - POSTGRES_PASSWORD
    image: ${DB_IMAGE_TAG:-registry.gitlab.com/hunter2.app/hunter2/db}
  metrics:
    build: ./prometheus
    image: ${METRICS_IMAGE_TAG:-registry.gitlab.com/hunter2.app/hunter2/metrics}
  web:
    build: ./nginx
    image: ${WEB_IMAGE_TAG:-registry.gitlab.com/hunter2.app/hunter2/web}
