version: '2.1'

services:
  poetry:
    entrypoint: poetry
    environment:
      PATH: /opt/hunter2/venv/bin:/root/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      VIRTUAL_ENV: /opt/hunter2/venv
    image: ${PYTHON_IMAGE_TAG:-registry.gitlab.com/hunter2.app/hunter2/python:latest}
    volumes:
      - ${PWD:-.}:/opt/hunter2/src
  dot:
    command: -v -Tsvg -o/files/diagram/models.svg /files/diagram/models.dot
    image: registry.gitlab.com/rconan/docker-graphviz:3.0.0-39@sha256:68ddec0deff1d737775e28725e26f703406c5327e4dbdfab8850d475857ac8bb
    volumes:
      - ${PWD:-.}:/files
  eslint:
    command: ["."]
    image: registry.gitlab.com/rconan/docker-eslint:8.28.0-3@sha256:f2cf2e4d775a20cdf2a98eb96215a51fcfda38049023bd6102ee2838a23a4ed0
    volumes:
      - ${PWD:-.}:/code
  flake8:
    image: registry.gitlab.com/rconan/docker-flake8:5.0.0-22@sha256:22ff5c808ff71c5c81b9bdca3e9c788063c3dbb993c2ba732cf237bee46b25e6
    volumes:
      - ${PWD:-.}:/code
  docs:
    environment:
      - H2_IMAGE_VERSION
    image: ${H2_REGISTRY:-registry.gitlab.com/hunter2.app/hunter2}/app:${H2_IMAGE_VERSION:-latest}
    volumes:
      - ${PWD:-.}:/opt/hunter2/src

