version: '2.1'

services:
  app:
    build: .
    depends_on:
      - db
      - redis
    environment:
      - H2_DEBUG
      - H2_DOMAIN
      - H2_TEST_SEED
      - H2_SENDFILE=sendfile.backends.nginx
      - H2_SENTRY_DSN
    image: ${APP_IMAGE_TAG:-registry.gitlab.com/hunter2.app/hunter2/app}
    volumes:
      - config:/config
      - uploads_events:/uploads/events
      - uploads_puzzles:/uploads/puzzles
      - uploads_solutions:/uploads/solutions
  db:
    image: postgres:9.6.16-alpine@sha256:3a1d32d67fff9d004a8fb50cbb4c7854dca176a9624ea12ba1bb9a5321e8eac1
    volumes:
      - db:/var/lib/postgresql/data
  db_exporter:
    depends_on:
      - db
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres@db:5432/?sslmode=disable
    image: wrouesnel/postgres_exporter:v0.8.0@sha256:520fcd04d6c8f922d800d89ae96c021f4afd22e376c4b88260a8b780e3375dbe
  metrics:
    build: ./prometheus
    image: ${METRICS_IMAGE_TAG:-registry.gitlab.com/hunter2.app/hunter2/metrics}
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - metrics:/prometheus
  redis:
    image: redis:5.0.10-alpine3.12@sha256:b38e34d20bfedc5a4331c97373e3508e8a7a855008ef9ba78d25887da36ce088
    volumes:
      - redis:/data
  redis_exporter:
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis://redis:6379
    image: oliver006/redis_exporter:v1.14.0-alpine@sha256:405253bea7451a7a872e5bfcfccd908b65b63132088750b4b2a28cd79ce9540d
  web:
    build: ./nginx
    depends_on:
      - app
    image: ${WEB_IMAGE_TAG:-registry.gitlab.com/hunter2.app/hunter2/web}
    ports:
      - 80
    volumes:
      - uploads_events:/media/events:ro
      - uploads_puzzles:/media/puzzles:ro
      - uploads_solutions:/media/solutions:ro

volumes:
  db: {}
  config: {}
  metrics: {}
  redis: {}
  uploads_events: {}
  uploads_puzzles: {}
  uploads_solutions: {}
