version: '2.1'

services:
  app:
    build: .
    depends_on:
      - db
      - redis
    environment:
      - H2_DEBUG
      - H2_DOMAIN
      - H2_TEST_SEED
      - H2_SENDFILE=sendfile.backends.nginx
      - H2_SENTRY_DSN
    image: ${APP_IMAGE_TAG:-registry.gitlab.com/hunter2.app/hunter2/app}
    volumes:
      - config:/config
      - uploads_events:/uploads/events
      - uploads_puzzles:/uploads/puzzles
      - uploads_site:/uploads/site
      - uploads_solutions:/uploads/solutions
  db:
    image: postgres:9.6.16-alpine@sha256:8ec15b51fd1ec3233ca7bcf3a58e800d863f57c8d07ffdc65fe4640a19f7b2e3
    volumes:
      - db:/var/lib/postgresql/data
  db_exporter:
    depends_on:
      - db
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres@db:5432/?sslmode=disable
    image: wrouesnel/postgres_exporter:v0.8.0@sha256:520fcd04d6c8f922d800d89ae96c021f4afd22e376c4b88260a8b780e3375dbe
  metrics:
    build: ./prometheus
    image: ${METRICS_IMAGE_TAG:-registry.gitlab.com/hunter2.app/hunter2/metrics}
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - metrics:/prometheus
  redis:
    image: redis:5.0.10-alpine3.12@sha256:cab1de051c243a956749397af796d50bf235c7183e88bc4667259f66cad4f748
    volumes:
      - redis:/data
  redis_exporter:
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis://redis:6379
    image: oliver006/redis_exporter:v1.17.0-alpine@sha256:4c1788200111ed25649c1d82cd0b86f553a264d6baabb6d1cd7482b0055fb299
  web:
    build: ./nginx
    depends_on:
      - app
    image: ${WEB_IMAGE_TAG:-registry.gitlab.com/hunter2.app/hunter2/web}
    ports:
      - 80
    volumes:
      - uploads_events:/media/events:ro
      - uploads_puzzles:/media/puzzles:ro
      - uploads_site:/media/site:ro
      - uploads_solutions:/media/solutions:ro

volumes:
  db: {}
  config: {}
  metrics: {}
  redis: {}
  uploads_events: {}
  uploads_puzzles: {}
  uploads_site: {}
  uploads_solutions: {}
