version: '3'

services:
  db:
    image: postgres:9.6
    volumes:
      - db:/var/lib/postgresql/data
  web:
    build: .
    depends_on:
      - db
    environment:
      - H2_DEBUG
    image: ${IMAGE_TAG:-hunter2}
    ports:
      - "8000:8000"
    volumes:
      - ${PWD:-.}:/usr/src/app
      - storage:/storage
      - config:/config

volumes:
  db: {}
  storage: {}
  config: {}