[tool.poetry]
name = "hunter2"
version = "0.4.0"
description = "A platform for creating and running online or event-based puzzle hunts"
authors = ["The Hunter 2 contributors"]
license = "AGPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.7"
Django = "^3.0"
PyYAML = "^5.1"
channels = "^2.3"
channels_redis = "^3.0"
colour-runner = "^0.1.1"
coverage = "^5.0"
daphne = "^2.3"
django-allauth = "^0.42.0"
django-analytical = "^2.5"
django-autocomplete-light = "^3.4"
django-bootstrap4 = "^2.1"
django-debug-toolbar = "^2.1"
django-enumfields = "^2.0"
django-environ = "^0.4.5"
django-extensions = "^3.0"
django-fullclean = { git = "https://github.com/riconnon/django-fullclean.git", tag = "0.0.4+whitelist" }
django-nested-admin = "^3.2"
django-ordered-model = { git = "https://github.com/fish-face/django-ordered-model.git", rev = "8a2908472b7bfbedb530a845f6c18fc86da7b750" }
django-prometheus = "^2.0"
django-sendfile = "^0.3.11"
django-solo = "^1.1"
django-sortedm2m = "^3.0"
django-tenants = "^3.0"
django-webpack-loader = "^0.7.0"
factory_boy = "^2.12"
freezegun = "^0.3.12"
lupa = "^1.8"
parameterized = "^0.7.1"
psycopg2 = "^2.8"
python3-openid = "^3.1"
rules = "^2.1"
sentry-sdk = "^0.16.0"
validators = "^0.16.0"
wait = "^0.0.3"
[tool.poetry.dev-dependencies]
django-silk = "^4.0.0"
ipython = "^7.11.1"
ptpython = "^3.0.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
