# Generated by Django 3.1.7 on 2021-04-25 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunter2', '0005_apitoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='script',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='script_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hunter2.file'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='style',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='style_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hunter2.file'),
        ),
    ]
