# Generated by Django 3.2.9 on 2021-11-16 19:32

from django.db import migrations, models


def populate_configuration_index_content(apps, schema_editor):
    Configuration = apps.get_model('hunter2', 'Configuration')
    Event = apps.get_model('events', 'event')
    config, _ = Configuration.objects.get_or_create()
    try:
        config.index_content = Event.objects.get(current=True).index_text
        config.save()
    except Event.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_index_text'),
        ('hunter2', '0006_auto_20210425_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='index_content',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(
            code=migrations.RunPython.noop,
            reverse_code=populate_configuration_index_content,
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='index_content',
        ),
    ]
