# Generated by Django 3.2.12 on 2022-03-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunter2', '0007_remove_configuration_index_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='captcha_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='captcha_question',
            field=models.TextField(blank=True),
        ),
    ]
