# Generated by Django 3.2.12 on 2022-03-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunter2', '0007_remove_configuration_index_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='captcha_answer',
            field=models.TextField(blank=True, help_text='The answer required to be given to the captcha question. Answer is case insensitive.'),

        ),
        migrations.AddField(
            model_name='configuration',
            name='captcha_question',
            field=models.TextField(blank=True, help_text='A static question to be asked on the signup form to attempt to deter bot signups. If blank no question is asked.'),
        ),
    ]
