# Generated by Django 3.1.7 on 2021-07-02 12:58

from django.db import migrations, models
import django.db.models.deletion


def populate_episode_dag(apps, schema_editor):
    Episode = apps.get_model('hunts', 'Episode')
    for episode in Episode.objects.all():
        for prequel in episode.prequels.all():
            Episode.children.through(parent=prequel, child=episode).save()


def populate_episode_prequels(apps, schema_editor):
    Episode = apps.get_model('hunts', 'Episode')
    for episode in Episode.objects.all():
        for prequel in episode.prequels.all():
            episode.prequels.add(prequel)


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0007_auto_20201117_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodePrequel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_edges', to='hunts.episode')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_edges', to='hunts.episode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='episode',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parents', through='hunts.EpisodePrequel', to='hunts.Episode'),
        ),
        migrations.RunPython(
            code=populate_episode_dag,
            reverse_code=populate_episode_prequels,
        ),
        migrations.RemoveField(
            model_name='episode',
            name='prequels',
        ),
    ]
