# Generated by Django 3.1.7 on 2021-06-20 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0008_auto_20210425_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teampuzzledata',
            name='start_time',
        ),
    ]
