# Generated by Django 3.1.7 on 2021-07-06 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0009_remove_teampuzzledata_start_time'),
        ('hunts', '0008_auto_20210702_1258'),
    ]

    operations = [
    ]
