# Generated by Django 3.1.7 on 2021-08-25 21:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0011_auto_20210723_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='guess',
            name='given',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
