# Generated by Django 3.1.7 on 2021-09-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0012_auto_20210825_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guess',
            name='guess',
            field=models.TextField(max_length=512),
        ),
    ]
