# Generated by Django 2.1.7 on 2019-02-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0016_auto_20190207_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='runtime',
            field=models.CharField(choices=[('S', 'Static'), ('s', 'Case Sensitive Static'), ('R', 'Regex'), ('r', 'Case Sensitive Regex'), ('I', 'IFrame'), ('L', 'Lua'), ('F', 'FaaS')], default='S', help_text='Processor to use to check whether guess is correct', max_length=1, verbose_name='Validator'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='cb_runtime',
            field=models.CharField(choices=[('S', 'Static'), ('s', 'Case Sensitive Static'), ('R', 'Regex'), ('r', 'Case Sensitive Regex'), ('I', 'IFrame'), ('L', 'Lua'), ('F', 'FaaS')], default='S', help_text='Processor used to execute the callback script in response to AJAX requests', max_length=1, verbose_name='AJAX callback processor'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='runtime',
            field=models.CharField(choices=[('S', 'Static'), ('s', 'Case Sensitive Static'), ('R', 'Regex'), ('r', 'Case Sensitive Regex'), ('I', 'IFrame'), ('L', 'Lua'), ('F', 'FaaS')], default='S', help_text='Renderer for generating the main puzzle page', max_length=1, verbose_name='Puzzle page renderer'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='soln_runtime',
            field=models.CharField(choices=[('S', 'Static'), ('s', 'Case Sensitive Static'), ('R', 'Regex'), ('r', 'Case Sensitive Regex'), ('I', 'IFrame'), ('L', 'Lua'), ('F', 'FaaS')], default='S', help_text='Renderer for generating the question solution', max_length=1, verbose_name='Solution renderer'),
        ),
        migrations.AlterField(
            model_name='unlockanswer',
            name='runtime',
            field=models.CharField(choices=[('S', 'Static'), ('s', 'Case Sensitive Static'), ('R', 'Regex'), ('r', 'Case Sensitive Regex'), ('I', 'IFrame'), ('L', 'Lua'), ('F', 'FaaS')], default='S', help_text='Processor to use to check whether guess unlocks this unlock', max_length=1, verbose_name='Validator'),
        ),
    ]
