# Generated by Django 3.2.11 on 2022-01-27 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

relations = (('guess', 'by'), ('userdata', 'user'), ('userpuzzledata', 'user'))
relation_cache = {}


def cache_user_relations(apps, schema_editor):
    for relation in relations:
        model = apps.get_model('hunts', relation[0])
        relation_cache[relation] = dict()
        for item in model.objects.all().prefetch_related(relation[1]):
            relation_cache[relation][item.id] = getattr(item, relation[1]).user.id
            setattr(item, relation[1], None)
            item.save()


def cache_user_profile_relations(apps, schema_editor):
    for relation in relations:
        model = apps.get_model('hunts', relation[0])
        relation_cache[relation] = dict()
        for item in model.objects.all().prefetch_related(relation[1]):
            relation_cache[relation][item.id] = getattr(item, relation[1]).profile.id
            setattr(item, relation[1], None)
            item.save()


def restore_relations(apps, schema_editor):
    for relation in relations:
        model = apps.get_model('hunts', relation[0])
        for item_id, user_id in relation_cache[relation].items():
            item = model.objects.get(id=item_id)
            setattr(item, relation[1] + '_id', user_id)
            item.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hunts', '0018_auto_20220127_2354'),
    ]

    operations = [
        migrations.RunPython(
            code=cache_user_relations,
            reverse_code=restore_relations,
        ),
        migrations.AlterField(
            model_name='guess',
            name='by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpuzzledata',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(
            code=restore_relations,
            reverse_code=cache_user_profile_relations,
        ),
    ]
