# Generated by Django 3.2.12 on 2022-03-13 13:15

from django.db import migrations
import enumfields.fields
import hunts.models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0020_auto_20220127_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='notify',
            field=enumfields.fields.EnumField(default='N', enum=hunts.models.AnnouncementNotificationOption, max_length=1),
        ),
    ]
