# Generated by Django 3.2.12 on 2022-04-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0021_announcement_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='guess',
            name='late',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teampuzzleprogress',
            name='late',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
