# Generated by Django 3.2.15 on 2022-09-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0022_auto_20220417_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unlock',
            name='text',
            field=models.TextField(blank=True, help_text='Text displayed when this clue is unlocked'),
        ),
        migrations.AlterUniqueTogether(
            name='hint',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='unlock',
            unique_together=set(),
        ),
    ]
