# Generated by Django 3.2.16 on 2022-10-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0024_auto_20221002_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='hint',
            name='obsoleted_by',
            field=models.ManyToManyField(
                blank=True,
                help_text='Any unlock added here will, when unlocked, cause this hint to be immediately revealed.',
                related_name='obsoletes', to='hunts.Unlock', verbose_name='Reveal after Unlock'
                ),
        ),
    ]
