# Generated by Django 3.2.16 on 2022-10-31 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0024_auto_20221002_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='no_stats',
            field=models.BooleanField(default=False, verbose_name='Excluded from public stats', help_text='Whether this episode should be excluded from public facing stats pages'),
        ),
    ]
