# Generated by Django 3.2.16 on 2022-10-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0024_auto_20221002_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='unlock',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
