# Generated by Django 3.2.16 on 2022-11-11 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0025_episode_no_stats'),
        ('hunts', '0025_hint_obsoleted_by'),
    ]

    operations = [
    ]
