# Generated by Django 3.2.11 on 2022-01-15 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211115_2034'),
    ]

    operations = [
        # This migration used to add the `gdpr_assist.models.CastPrivacyManager` manager to `user`.
        # In django-gdpr-assist version >=1.4 this manager no longer exists, so the migration can no longer be applied, even if it would later be reverted by a
        # future migration.
        # Since the custom manager behaviour is never depended on in a future migration and manager information is not persisted in the database it is safe to
        # simply remove the migration operation.
        # This migration has been left in place with no operations to keep the migration dependencies intact until it is squashed away in the future.
    ]
