# Generated by Django 3.2.11 on 2022-01-15 00:59

from django.db import migrations
import gdpr_assist.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211115_2034'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', gdpr_assist.models.CastPrivacyUserManager()),
            ],
        ),
    ]
