# Generated by Django 3.2.9 on 2021-11-18 09:24

import uuid

from django.db import migrations, models


def populate_user_fields(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    for user in User.objects.all():
        # This makes a new UUID which means profile URLs will change.
        # Unfortunately this is necessary since we can't make the events migration which
        # migrates the Attendance reference to User run in the same transaction
        user.uuid = uuid.uuid4()
        if user.info:
            user.contact = user.info.contact
            user.picture = user.info.picture
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211115_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.BooleanField(help_text="We won't spam you, only important information about our events.", null=True, verbose_name='May we contact you?'),
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.URLField(blank=True, help_text='Paste a URL to an image for your profile picture'),
        ),
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(editable=False, null=True, serialize=False),
        ),
        migrations.RunPython(
            code=populate_user_fields,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, serialize=False, unique=True),
        ),
    ]
