# Generated by Django 3.2.11 on 2022-01-20 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_managers'),
        ('accounts', '0008_delete_userinfo'),
    ]

    operations = [
    ]
